param()

$ErrorActionPreference = 'Stop'

Write-Host "Running CI check for prompt construction boundary..."

# We want to find places where we use `router.route(` or `gateway.` 
# but the messages or prompt arg is being built with f-strings or .format directly
# rather than passing LLMMessages generated by PromptBuilder.

# This is a heuristic check. It looks for `.route(` or `.generate(` etc.
# in Python files and checks if the preceding lines use f-strings to build prompts.
# Specifically, we flag `messages=[{"role": "user", "content": f"...` 
# or `prompt=f"...` in router/gateway calls.

$files = Get-ChildItem -Path d:\work\interviewOS -Recurse -Include *.py -Exclude "check-prompt-construction-boundary.ps1", "test_*.py" | Where-Object { $_.FullName -notmatch "\\.venv\\" }

$violations = 0

foreach ($file in $files) {
    # Skip prompt_builder.py itself
    if ($file.Name -eq "prompt_builder.py") { continue }
    
    $content = Get-Content $file.FullName
    
    for ($i = 0; $i -lt $content.Length; $i++) {
        $line = $content[$i]
        
        # Check for router.route or gateway. calls
        if ($line -match "\.route\(" -or $line -match "\.generate\(" -or $line -match "\.stream\(" -or $line -match "\.structured\(") {
            
            # Check the surrounding 5 lines for suspicious string concatenation
            $start = [Math]::Max(0, $i - 5)
            $end = [Math]::Min($content.Length - 1, $i + 5)
            
            $suspicious = $false
            for ($j = $start; $j -le $end; $j++) {
                $ctxLine = $content[$j]
                if ($ctxLine -match 'prompt\s*=\s*f["'']' -or $ctxLine -match 'content\["'']\s*:\s*f["'']' -or $ctxLine -match '\.format\(') {
                    $suspicious = $true
                    break
                }
            }
            
            if ($suspicious) {
                Write-Host "::warning file=$($file.FullName),line=$($i+1)::Suspicious prompt construction detected."
                Write-Host "  Found router/gateway call near f-string or .format(). Use PromptBuilder instead."
                Write-Host "  Context: $line"
                $violations++
            }
        }
    }
}

Write-Host "Found $violations suspicious prompt construction(s)."
Write-Host "NOTE: This is a heuristic check. Known limitations: It may flag legitimate logging near router calls, or miss complex multi-line concatenation. It only catches naive f-string/format usages passed to the router."

if ($violations -gt 0) {
    # We will just warn for now or exit with 0 to not block the build if there are existing violations we aren't meant to fix right now, 
    # but the prompt says it's a CI boundary check. Let's return exit code 1 to enforce it!
    exit 1
}

exit 0
