-- ============================================================================
-- RECONCILE SCHEMA (2026-10-04)
-- Brings the canonical schema in line with backend/app/db/models.py and the
-- API/worker code. Fully idempotent: safe to re-run.
-- ============================================================================

-- ── 1. created_at / updated_at on every table ───────────────────────────────
alter table session_state_log add column if not exists updated_at timestamptz not null default now();
alter table study_reviews     add column if not exists updated_at timestamptz not null default now();
alter table model_requests    add column if not exists updated_at timestamptz not null default now();
alter table usage_events      add column if not exists updated_at timestamptz not null default now();
alter table audit_logs        add column if not exists updated_at timestamptz not null default now();
alter table privacy_events    add column if not exists updated_at timestamptz not null default now();
alter table failed_jobs       add column if not exists created_at timestamptz not null default now();
alter table failed_jobs       add column if not exists updated_at timestamptz not null default now();

do $$
declare t text;
begin
  foreach t in array array['session_state_log','study_reviews','model_requests','usage_events',
                           'audit_logs','privacy_events','failed_jobs']
  loop
    if not exists (select 1 from pg_trigger where tgname = 'trg_' || t || '_updated_at') then
      execute format('create trigger %I before update on %I for each row execute function set_updated_at()',
                     'trg_' || t || '_updated_at', t);
    end if;
  end loop;
end $$;

-- ── 2. Columns referenced by the application ───────────────────────────────
alter table profiles add column if not exists is_banned boolean not null default false;
alter table profiles add column if not exists paid_provider_acknowledged boolean not null default false;
alter table practice_sessions add column if not exists focus_area text;

-- Sessions are created (pending) by the API before the realtime socket starts them.
alter table practice_sessions drop constraint if exists practice_sessions_status_check;
alter table practice_sessions add constraint practice_sessions_status_check
  check (status in ('pending','active','completed','abandoned','failed'));

-- Study items can be generated by the study-material job.
alter table study_items drop constraint if exists study_items_source_check;
alter table study_items add constraint study_items_source_check
  check (source in ('weak_answer','missed_concept','jd_gap','manual','screenshot_solve','generated'));

-- ── 3. FK behaviour ────────────────────────────────────────────────────────
-- Deleting a saved job must not silently delete the candidate's practice
-- history; detach instead.
alter table practice_sessions drop constraint if exists practice_sessions_job_id_fkey;
alter table practice_sessions add constraint practice_sessions_job_id_fkey
  foreign key (job_id) references jobs(id) on delete set null;

-- One candidate row per auth profile (only enforced if data is already clean,
-- so this migration never fails on legacy duplicates).
do $$
begin
  if not exists (select 1 from pg_indexes where indexname = 'uq_candidates_profile_id') then
    if not exists (select profile_id from candidates group by profile_id having count(*) > 1) then
      create unique index uq_candidates_profile_id on candidates(profile_id);
    else
      raise notice 'candidates.profile_id has duplicates; creating non-unique index instead';
      create index if not exists idx_candidates_profile_id on candidates(profile_id);
    end if;
  end if;
end $$;

-- ── 4. Indexes for ownership filters, FK joins and keyset pagination ───────
create index if not exists idx_documents_candidate_created        on documents (candidate_id, created_at desc, id desc);
create index if not exists idx_resumes_candidate_created          on resumes (candidate_id, created_at desc, id desc);
create index if not exists idx_resumes_document_id                on resumes (document_id);
create index if not exists idx_resume_versions_resume_id          on resume_versions (resume_id);
create index if not exists idx_resume_claims_version_id           on resume_claims (resume_version_id);
create index if not exists idx_jobs_candidate_created             on jobs (candidate_id, created_at desc, id desc);
create index if not exists idx_job_requirements_blueprint_id      on job_requirements (job_blueprint_id);
create index if not exists idx_job_matches_candidate_id           on job_matches (candidate_id);
create index if not exists idx_practice_sessions_job_id           on practice_sessions (job_id);
create index if not exists idx_session_state_log_session_time     on session_state_log (session_id, occurred_at);
create index if not exists idx_transcript_segments_session_id     on transcript_segments (session_id);
create index if not exists idx_transcript_segments_turn_id        on transcript_segments (turn_id);
create index if not exists idx_session_claims_turn_id             on session_claims (turn_id);
create index if not exists idx_study_items_candidate_created      on study_items (candidate_id, created_at desc, id desc);
create index if not exists idx_study_reviews_item_id              on study_reviews (item_id);
create index if not exists idx_screenshot_tasks_candidate_id      on screenshot_tasks (candidate_id);
create index if not exists idx_solver_results_task_id             on solver_results (screenshot_task_id);
create index if not exists idx_applications_candidate_created     on applications (candidate_id, created_at desc, id desc);
create index if not exists idx_application_events_application_id  on application_events (application_id);
create index if not exists idx_outreach_drafts_application_id     on outreach_drafts (application_id);
create index if not exists idx_stories_candidate_id               on stories (candidate_id);
create index if not exists idx_candidate_experiences_candidate_id on candidate_experiences (candidate_id);
create index if not exists idx_candidate_education_candidate_id   on candidate_education (candidate_id);
create index if not exists idx_candidate_certs_candidate_id       on candidate_certifications (candidate_id);
create index if not exists idx_project_metrics_project_id         on project_metrics (project_id);
create index if not exists idx_user_settings_candidate_id         on user_settings (candidate_id);
create index if not exists idx_usage_events_session_id            on usage_events (session_id);
create index if not exists idx_deletion_jobs_profile_id           on deletion_jobs (profile_id);
create index if not exists idx_failed_jobs_candidate_id           on failed_jobs (candidate_id);
create index if not exists idx_failed_jobs_unresolved             on failed_jobs (failed_at) where resolved = false;
